<?php
/**
 * Template Name: Zásady cookies
 * Figma node 685:85: Legal page with TOC sidebar, content area.
 *
 * @package Xevos\CyberTheme
 */

get_header();
?>

<main id="main" class="xevos-main">
	<?php echo xevos_breadcrumbs(); ?>

	<?php while ( have_posts() ) : the_post(); ?>
		<article class="xevos-section xevos-legal">
			<div class="xevos-section__container xevos-legal__container">
				<h1 class="xevos-legal__title"><?php the_title(); ?></h1>

				<?php $datum_aktualizace = get_field( 'datum_posledni_aktualizace' ); ?>
				<?php if ( $datum_aktualizace ) : ?>
					<p class="xevos-legal__date">
						<?php printf( esc_html__( 'Poslední aktualizace: %s', 'xevos-cyber' ), esc_html( $datum_aktualizace ) ); ?>
					</p>
				<?php endif; ?>

				<!-- TOC generated by JS from h2/h3 -->
				<nav class="xevos-toc" id="toc" aria-label="<?php esc_attr_e( 'Obsah stránky', 'xevos-cyber' ); ?>"></nav>

				<div class="xevos-legal-content" id="legal-content">
					<?php
					$content = get_the_content();
					if ( $content ) :
						the_content();
					else : ?>
						<h2>Co jsou cookies</h2>
						<p>Cookies jsou malé textové soubory, které se ukládají do vašeho prohlížeče při návštěvě webových stránek. Slouží k zajištění správného fungování webu, analýze návštěvnosti a personalizaci obsahu.</p>

						<h2>Jaké cookies používáme</h2>

						<h3>Nezbytné cookies</h3>
						<p>Tyto cookies jsou nutné pro správné fungování webu. Nelze je vypnout. Zahrnují cookies pro správu relace, bezpečnostní tokeny a preference souhlasu s cookies.</p>

						<h3>Analytické cookies</h3>
						<p>Pomáhají nám porozumět, jak návštěvníci používají naše stránky. Data jsou anonymizována. Používáme Google Analytics 4.</p>

						<h3>Marketingové cookies</h3>
						<p>Slouží k zobrazování relevantních reklam a měření účinnosti reklamních kampaní. Používají se pouze s vaším výslovným souhlasem.</p>

						<h2>Správa cookies</h2>
						<p>Při první návštěvě webu vás požádáme o souhlas s používáním volitelných cookies. Svůj souhlas můžete kdykoliv odvolat nebo změnit v nastavení cookies na našem webu nebo v nastavení vašeho prohlížeče.</p>

						<h2>Doba uchovávání</h2>
						<p>Nezbytné cookies: po dobu relace nebo max. 1 rok. Analytické cookies: max. 26 měsíců. Marketingové cookies: max. 12 měsíců.</p>

						<h2>Další informace</h2>
						<p>Podrobnosti o zpracování osobních údajů naleznete v <a href="<?php echo esc_url( home_url( '/zasady-ochrany-osobnich-udaju/' ) ); ?>">Zásadách ochrany osobních údajů</a>. V případě dotazů nás kontaktujte na hello@xevos.eu.</p>
					<?php endif; ?>
				</div>
			</div>
		</article>
	<?php endwhile; ?>
</main>

<script>
document.addEventListener('DOMContentLoaded', () => {
	const content = document.getElementById('legal-content');
	const toc = document.getElementById('toc');
	if (!content || !toc) return;

	const headings = content.querySelectorAll('h2, h3');
	if (headings.length < 2) return;

	let html = '<h4><?php esc_html_e( 'Obsah', 'xevos-cyber' ); ?></h4><ol>';
	headings.forEach((h, i) => {
		const id = `section-${i}`;
		h.id = id;
		const indent = h.tagName === 'H3' ? ' style="margin-left:1.5rem;"' : '';
		html += `<li${indent}><a href="#${id}">${h.textContent}</a></li>`;
	});
	html += '</ol>';
	toc.innerHTML = html;
});
</script>

<?php
get_footer();
