<?php
/**
 * Template Name: Zásady ochrany osobních údajů
 * Figma node 685:85: Legal page with TOC sidebar, content area.
 *
 * @package Xevos\CyberTheme
 */

get_header();
?>

<main id="main" class="xevos-main">
	<?php echo xevos_breadcrumbs(); ?>

	<?php while ( have_posts() ) : the_post(); ?>
		<article class="xevos-section xevos-legal">
			<div class="xevos-section__container xevos-legal__container">
				<h1 class="xevos-legal__title"><?php the_title(); ?></h1>

				<?php $datum_aktualizace = get_field( 'datum_posledni_aktualizace' ); ?>
				<?php if ( $datum_aktualizace ) : ?>
					<p class="xevos-legal__date">
						<?php printf( esc_html__( 'Poslední aktualizace: %s', 'xevos-cyber' ), esc_html( $datum_aktualizace ) ); ?>
					</p>
				<?php endif; ?>

				<!-- TOC generated by JS from h2/h3 -->
				<nav class="xevos-toc" id="toc" aria-label="<?php esc_attr_e( 'Obsah stránky', 'xevos-cyber' ); ?>"></nav>

				<div class="xevos-legal-content" id="legal-content">
					<?php
					$content = get_the_content();
					if ( $content ) :
						the_content();
					else : ?>
						<h2>Správce osobních údajů</h2>
						<p>Správcem osobních údajů je společnost XEVOS Solutions s.r.o., IČO: 14184290, se sídlem Mostárenská 1156/38, 703 00 Ostrava (dále jen „Správce"). Kontaktní e-mail: hello@xevos.eu.</p>

						<h2>Rozsah zpracování osobních údajů</h2>
						<p>Zpracováváme osobní údaje, které nám poskytnete v rámci objednávky služeb, registrace na školení nebo kontaktního formuláře. Jedná se zejména o: jméno a příjmení, e-mailovou adresu, telefonní číslo, fakturační údaje (název firmy, IČO, DIČ, adresa).</p>

						<h2>Účel zpracování</h2>
						<p>Osobní údaje zpracováváme za účelem: plnění smlouvy a poskytování objednaných služeb, zasílání informací o objednávce a fakturace, komunikace s klienty, plnění zákonných povinností (účetnictví, daňová evidence), zasílání obchodních sdělení (pouze s vaším souhlasem).</p>

						<h3>Právní základ zpracování</h3>
						<p>Zpracování je založeno na: plnění smlouvy (čl. 6 odst. 1 písm. b) GDPR), oprávněném zájmu správce (čl. 6 odst. 1 písm. f) GDPR), plnění právní povinnosti (čl. 6 odst. 1 písm. c) GDPR), souhlasu subjektu údajů (čl. 6 odst. 1 písm. a) GDPR).</p>

						<h2>Doba uchovávání údajů</h2>
						<p>Osobní údaje uchováváme po dobu nezbytnou k naplnění účelu zpracování, nejdéle však po dobu stanovenou příslušnými právními předpisy (typicky 10 let pro účetní doklady).</p>

						<h2>Příjemci osobních údajů</h2>
						<p>Vaše údaje mohou být předány poskytovatelům služeb, kteří pro nás zajišťují zpracování dat (hosting, fakturace, e-mailové služby). Všichni příjemci jsou vázáni povinností mlčenlivosti a zpracovávají údaje pouze dle našich pokynů.</p>

						<h2>Vaše práva</h2>
						<p>Máte právo na přístup k údajům, opravu, výmaz, omezení zpracování, přenositelnost údajů a právo vznést námitku. Svá práva můžete uplatnit na e-mailu hello@xevos.eu. Máte rovněž právo podat stížnost u Úřadu pro ochranu osobních údajů (www.uoou.cz).</p>

						<h2>Zabezpečení údajů</h2>
						<p>Přijali jsme vhodná technická a organizační opatření k ochraně vašich osobních údajů před neoprávněným přístupem, změnou, ztrátou nebo zničením.</p>

						<h2>Cookies</h2>
						<p>Informace o používání cookies naleznete v samostatném dokumentu <a href="<?php echo esc_url( home_url( '/zasady-cookies/' ) ); ?>">Zásady cookies</a>.</p>
					<?php endif; ?>
				</div>
			</div>
		</article>
	<?php endwhile; ?>
</main>

<script>
document.addEventListener('DOMContentLoaded', () => {
	const content = document.getElementById('legal-content');
	const toc = document.getElementById('toc');
	if (!content || !toc) return;

	const headings = content.querySelectorAll('h2, h3');
	if (headings.length < 2) return;

	let html = '<h4><?php esc_html_e( 'Obsah', 'xevos-cyber' ); ?></h4><ol>';
	headings.forEach((h, i) => {
		const id = `section-${i}`;
		h.id = id;
		const indent = h.tagName === 'H3' ? ' style="margin-left:1.5rem;"' : '';
		html += `<li${indent}><a href="#${id}">${h.textContent}</a></li>`;
	});
	html += '</ol>';
	toc.innerHTML = html;
});
</script>

<?php
get_footer();
