<?php
/**
 * Template Name: Obchodní podmínky
 * Figma node 685:85: Legal page with TOC sidebar, content area.
 *
 * @package Xevos\CyberTheme
 */

get_header();
?>

<main id="main" class="xevos-main">
	<?php echo xevos_breadcrumbs(); ?>

	<?php while ( have_posts() ) : the_post(); ?>
		<article class="xevos-section xevos-legal">
			<div class="xevos-section__container xevos-legal__container">
				<h1 class="xevos-legal__title"><?php the_title(); ?></h1>

				<?php $datum_aktualizace = get_field( 'datum_posledni_aktualizace' ); ?>
				<?php if ( $datum_aktualizace ) : ?>
					<p class="xevos-legal__date">
						<?php printf( esc_html__( 'Poslední aktualizace: %s', 'xevos-cyber' ), esc_html( $datum_aktualizace ) ); ?>
					</p>
				<?php endif; ?>

				<!-- TOC generated by JS from h2/h3 -->
				<nav class="xevos-toc" id="toc" aria-label="<?php esc_attr_e( 'Obsah stránky', 'xevos-cyber' ); ?>"></nav>

				<div class="xevos-legal-content" id="legal-content">
					<?php
					$content = get_the_content();
					if ( $content ) :
						the_content();
					else : ?>
						<h2>Úvodní ustanovení</h2>
						<p>Tyto obchodní podmínky společnosti XEVOS Solutions s.r.o., IČO: 14184290, se sídlem Mostárenská 1156/38, 703 00 Ostrava (dále jen „Poskytovatel"), upravují vzájemná práva a povinnosti smluvních stran vzniklé v souvislosti s objednávkou služeb.</p>

						<h2>Předmět smlouvy</h2>
						<p>Předmětem smlouvy je poskytování služeb v oblasti kybernetické bezpečnosti, včetně školení, penetračních testů, auditů a poradenství dle aktuální nabídky Poskytovatele.</p>

						<h2>Objednávka a uzavření smlouvy</h2>
						<p>Objednávka je závazná okamžikem jejího odeslání prostřednictvím objednávkového formuláře. Smlouva je uzavřena potvrzením objednávky ze strany Poskytovatele.</p>

						<h2>Cena a platební podmínky</h2>
						<p>Ceny jsou uvedeny včetně DPH, není-li výslovně uvedeno jinak. Platba probíhá na základě faktury se splatností 14 dní, případně online platbou při objednávce.</p>

						<h2>Storno podmínky</h2>
						<p>Objednavatel může bezplatně zrušit objednávku školení nejpozději 7 pracovních dnů před termínem konání. Při pozdějším zrušení může být účtován storno poplatek ve výši 50 % ceny.</p>

						<h2>Reklamace</h2>
						<p>V případě nespokojenosti s poskytnutou službou je Objednavatel oprávněn uplatnit reklamaci písemně do 14 dnů od poskytnutí služby na e-mail hello@xevos.eu.</p>

						<h2>Závěrečná ustanovení</h2>
						<p>Tyto obchodní podmínky nabývají účinnosti dnem jejich zveřejnění. Poskytovatel si vyhrazuje právo na jejich změnu. Vztahy těmito podmínkami výslovně neupravené se řídí právním řádem České republiky.</p>
					<?php endif; ?>
				</div>
			</div>
		</article>
	<?php endwhile; ?>
</main>

<script>
document.addEventListener('DOMContentLoaded', () => {
	const content = document.getElementById('legal-content');
	const toc = document.getElementById('toc');
	if (!content || !toc) return;

	const headings = content.querySelectorAll('h2, h3');
	if (headings.length < 2) return;

	let html = '<h4><?php esc_html_e( 'Obsah', 'xevos-cyber' ); ?></h4><ol>';
	headings.forEach((h, i) => {
		const id = `section-${i}`;
		h.id = id;
		const indent = h.tagName === 'H3' ? ' style="margin-left:1.5rem;"' : '';
		html += `<li${indent}><a href="#${id}">${h.textContent}</a></li>`;
	});
	html += '</ol>';
	toc.innerHTML = html;
});
</script>

<?php
get_footer();
