<?php
/**
 * Template: Legal pages (Obchodní podmínky, GDPR, Cookies).
 * Template Name: Právní stránka
 *
 * @package Xevos\CyberTheme
 */

get_header();
?>

<main id="main" class="xevos-main">
	<?php echo xevos_breadcrumbs(); ?>

	<?php while ( have_posts() ) : the_post(); ?>
		<article class="xevos-section">
			<div class="xevos-section__container" style="max-width:1200px;">
				<h1><?php the_title(); ?></h1>

				<?php $datum_aktualizace = get_field( 'datum_posledni_aktualizace' ); ?>
				<?php if ( $datum_aktualizace ) : ?>
					<p style="color:var(--color-text-light);font-size:0.875rem;margin-bottom:2rem;">
						<?php printf( esc_html__( 'Poslední aktualizace: %s', 'xevos-cyber' ), esc_html( $datum_aktualizace ) ); ?>
					</p>
				<?php endif; ?>

				<!-- TOC generated by JS from h2/h3 -->
				<nav class="xevos-toc" id="toc" aria-label="<?php esc_attr_e( 'Obsah stránky', 'xevos-cyber' ); ?>"></nav>

				<div class="xevos-legal-content" id="legal-content">
					<?php the_content(); ?>
				</div>
			</div>
		</article>
	<?php endwhile; ?>


<script>
// Generate TOC from h2/h3.
document.addEventListener('DOMContentLoaded', () => {
	const content = document.getElementById('legal-content');
	const toc = document.getElementById('toc');
	if (!content || !toc) return;

	const headings = content.querySelectorAll('h2, h3');
	if (headings.length < 2) return;

	let html = '<h4><?php esc_html_e( 'Obsah', 'xevos-cyber' ); ?></h4><ol>';
	headings.forEach((h, i) => {
		const id = `section-${i}`;
		h.id = id;
		const indent = h.tagName === 'H3' ? ' style="margin-left:1.5rem;"' : '';
		html += `<li${indent}><a href="#${id}">${h.textContent}</a></li>`;
	});
	html += '</ol>';
	toc.innerHTML = html;
});
</script>

<?php
get_footer();
